name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Build 
        run: npm run build 

      - name: Run unit tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success()

    steps:
      - name: Connect to Staging Server via SSH
        run: |
          echo "Connecting to staging environment on Ubuntu EC2 instance..."
          ssh -i ${{ secrets.AWS_SSH_KEY }} ubuntu@${{ secrets.STAGING_SERVER }}
        env:
          AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
          STAGING_SERVER: ${{ secrets.STAGING_SERVER }}

    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v3

    #   - name: Deploy to Staging
    #     run: |
    #       echo "Deploying to staging server..."
    #       scp -r ./dist ubuntu@$staging-server:/var/www/html/
    #     env:
    #       name: Staging
    #       AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
    #       STAGING_SERVER: ${{ secrets.STAGING_SERVER }}
          
            
        



        